USE VITA2023
GO
--TOPLAM ÝHTÝYAÇ DUYULAN HAM_KODU ADET VE TÝPÝNÝ BUL
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC1', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC1; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC2', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC2; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC3', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC3; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC4', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC4; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC5', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC5; 
IF OBJECT_ID('dbo.dosTOPLAMIHTIYAC6', 'U') IS NOT NULL DROP TABLE dbo.dosTOPLAMIHTIYAC6; 
IF OBJECT_ID('dbo.dosPART1', 'U') IS NOT NULL DROP TABLE dbo.dosPART1; 
IF OBJECT_ID('dbo.dosPART2V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART2V1; 
IF OBJECT_ID('dbo.dosPART3V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART3V1; 
IF OBJECT_ID('dbo.dosPART4V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART4V1; 
IF OBJECT_ID('dbo.dosPART5V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART5V1; 
IF OBJECT_ID('dbo.dosPART6V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART6V1; 
IF OBJECT_ID('dbo.dosPART7V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART7V1; 
IF OBJECT_ID('dbo.dosPART8V1', 'U') IS NOT NULL DROP TABLE dbo.dosPART8V1; 
IF OBJECT_ID('dbo.dosPART2', 'U') IS NOT NULL DROP TABLE dbo.dosPART2; 
IF OBJECT_ID('dbo.dosPART3', 'U') IS NOT NULL DROP TABLE dbo.dosPART3; 
IF OBJECT_ID('dbo.dosPART4', 'U') IS NOT NULL DROP TABLE dbo.dosPART4; 
IF OBJECT_ID('dbo.dosPART5', 'U') IS NOT NULL DROP TABLE dbo.dosPART5; 
IF OBJECT_ID('dbo.dosPART6', 'U') IS NOT NULL DROP TABLE dbo.dosPART6; 
IF OBJECT_ID('dbo.dosPART7', 'U') IS NOT NULL DROP TABLE dbo.dosPART7; 
IF OBJECT_ID('dbo.dosPART8', 'U') IS NOT NULL DROP TABLE dbo.dosPART8; 

--dosPART1
select b.HAM_KODU AS HAM_KODU1,SUM(MIKTAR) as BIRIM_MIKTAR1 INTO dosPART1 from SIPMAMULdos a left join TBLSTOKURM b ON a.MAMUL_KODU=b.MAMUL_KODU GROUP BY b.HAM_KODU

--dosPART2
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, b.HAM_KODU AS HAM_KODU2, (a.BIRIM_MIKTAR1*b.MIKTAR) AS BIRIM_MIKTAR2 INTO dosPART2 from dosPART1 a left join TBLSTOKURM b ON a.HAM_KODU1=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART2)) BEGIN
SELECT HAM_KODU2, SUM(BIRIM_MIKTAR2) AS BIRIM_MIKTAR2 INTO dosPART2V1 FROM dosPART2 GROUP BY HAM_KODU2 
INSERT INTO dosPART1 SELECT HAM_KODU2,BIRIM_MIKTAR2 FROM dosPART2V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC FROM dosPART1 GROUP BY HAM_KODU1
END;

--dosPART3
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, b.HAM_KODU AS HAM_KODU3, (a.BIRIM_MIKTAR2*b.MIKTAR) AS BIRIM_MIKTAR3 INTO dosPART3 from dosPART2 a left join TBLSTOKURM b ON a.HAM_KODU2=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART3)) BEGIN
SELECT HAM_KODU3, SUM(BIRIM_MIKTAR3) AS BIRIM_MIKTAR3 INTO dosPART3V1 FROM dosPART3 GROUP BY HAM_KODU3
INSERT INTO dosTOPLAMIHTIYAC SELECT HAM_KODU3,BIRIM_MIKTAR3 FROM dosPART3V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC1 FROM dosTOPLAMIHTIYAC GROUP BY HAM_KODU1 
END;

--dosPART4
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3, b.HAM_KODU AS HAM_KODU4, (a.BIRIM_MIKTAR3*b.MIKTAR) AS BIRIM_MIKTAR4 INTO dosPART4 from dosPART3 a left join TBLSTOKURM b ON a.HAM_KODU3=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART4)) BEGIN
SELECT HAM_KODU4, SUM(BIRIM_MIKTAR4) AS BIRIM_MIKTAR4 INTO dosPART4V1 FROM dosPART4 GROUP BY HAM_KODU4
INSERT INTO dosTOPLAMIHTIYAC1 SELECT HAM_KODU4,BIRIM_MIKTAR4 FROM dosPART4V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC2 FROM dosTOPLAMIHTIYAC1 GROUP BY HAM_KODU1
END;

--dosPART5
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4, b.HAM_KODU AS HAM_KODU5, (a.BIRIM_MIKTAR4*b.MIKTAR) AS BIRIM_MIKTAR5 INTO dosPART5 from dosPART4 a left join TBLSTOKURM b ON a.HAM_KODU4=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART5)) BEGIN
SELECT HAM_KODU5, SUM(BIRIM_MIKTAR5) AS BIRIM_MIKTAR5 INTO dosPART5V1 FROM dosPART5 GROUP BY HAM_KODU5
INSERT INTO dosTOPLAMIHTIYAC2 SELECT HAM_KODU5,BIRIM_MIKTAR5 FROM dosPART5V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC3 FROM dosTOPLAMIHTIYAC2 GROUP BY HAM_KODU1 
END;

--dosPART6
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5, b.HAM_KODU AS HAM_KODU6, (a.BIRIM_MIKTAR5*b.MIKTAR) AS BIRIM_MIKTAR6 INTO dosPART6 from dosPART5 a left join TBLSTOKURM b ON a.HAM_KODU5=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART6)) BEGIN
SELECT HAM_KODU6, SUM(BIRIM_MIKTAR6) AS BIRIM_MIKTAR6 INTO dosPART6V1 FROM dosPART6 GROUP BY HAM_KODU6
INSERT INTO dosTOPLAMIHTIYAC3 SELECT HAM_KODU6,BIRIM_MIKTAR6 FROM dosPART6V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC4 FROM dosTOPLAMIHTIYAC3 GROUP BY HAM_KODU1 
END;

--dosPART7
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5,a.HAM_KODU6,a.BIRIM_MIKTAR6, b.HAM_KODU AS HAM_KODU7, (a.BIRIM_MIKTAR6*b.MIKTAR) AS BIRIM_MIKTAR7 INTO dosPART7 from dosPART6 a left join TBLSTOKURM b ON a.HAM_KODU6=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART7)) BEGIN 
SELECT HAM_KODU7, SUM(BIRIM_MIKTAR7) AS BIRIM_MIKTAR7 INTO dosPART7V1 FROM dosPART7 GROUP BY HAM_KODU7
INSERT INTO dosTOPLAMIHTIYAC4 SELECT HAM_KODU7,BIRIM_MIKTAR7 FROM dosPART7V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC5 FROM dosTOPLAMIHTIYAC4 GROUP BY HAM_KODU1 ;
END;

--dosPART8
SELECT a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5,a.HAM_KODU6,a.BIRIM_MIKTAR6,a.HAM_KODU7,a.BIRIM_MIKTAR7, b.HAM_KODU AS HAM_KODU8, (a.BIRIM_MIKTAR7*b.MIKTAR) AS BIRIM_MIKTAR8 INTO dosPART8 from dosPART7 a left join TBLSTOKURM b ON a.HAM_KODU7=b.MAMUL_KODU WHERE b.HAM_KODU IS NOT NULL 
IF(EXISTS(SELECT 1 FROM dbo.dosPART8)) BEGIN 
SELECT HAM_KODU8, SUM(BIRIM_MIKTAR8) AS BIRIM_MIKTAR8 INTO dosPART8V1 FROM dosPART8 GROUP BY HAM_KODU8
INSERT INTO dosTOPLAMIHTIYAC5 SELECT HAM_KODU8,BIRIM_MIKTAR8 FROM dosPART8V1
SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) AS BIRIM_MIKTAR1 INTO dosTOPLAMIHTIYAC6 FROM dosTOPLAMIHTIYAC5 GROUP BY HAM_KODU1 
END;

--HER dosPARTI BÝR SONRAKÝ dosPARTA EKLEYÝP BENZERLERÝ SÝLEREK BÝR ÖNCEKÝ dosPARTTA HAM_KODU TÜKENENLERÝ YENÝ dosPARTA EKLEMÝÞ OL
IF(EXISTS(SELECT 1 FROM dbo.dosPART2)) BEGIN
INSERT INTO dosPART2 (HAM_KODU1,BIRIM_MIKTAR1) SELECT HAM_KODU1, SUM(BIRIM_MIKTAR1) FROM dosPART1 GROUP BY HAM_KODU1;
WITH CTE (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2, DuplicateCount) AS (SELECT HAM_KODU1, BIRIM_MIKTAR1, HAM_KODU2, ROW_NUMBER() OVER (PARTITION BY HAM_KODU1 ORDER BY HAM_KODU1) AS DuplicateCount FROM dosPART2) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU2 IS NULL
END;

IF(EXISTS(SELECT 1 FROM dbo.dosPART3)) BEGIN
INSERT INTO dosPART3 (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2,BIRIM_MIKTAR2) SELECT * FROM dosPART2;
WITH CTE (HAM_KODU2,BIRIM_MIKTAR2,HAM_KODU3, DuplicateCount) AS (SELECT HAM_KODU2, BIRIM_MIKTAR2, HAM_KODU3, ROW_NUMBER() OVER (PARTITION BY HAM_KODU2 ORDER BY HAM_KODU2) AS DuplicateCount FROM dosPART3) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU3 IS NULL AND HAM_KODU2 IS NOT NULL
END;

IF(EXISTS(SELECT 1 FROM dbo.dosPART4)) BEGIN
INSERT INTO dosPART4 (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2,BIRIM_MIKTAR2,HAM_KODU3,BIRIM_MIKTAR3) SELECT * FROM dosPART3;
WITH CTE (HAM_KODU3,BIRIM_MIKTAR3,HAM_KODU4, DuplicateCount) AS (SELECT HAM_KODU3, BIRIM_MIKTAR3, HAM_KODU4, ROW_NUMBER() OVER (PARTITION BY HAM_KODU3 ORDER BY HAM_KODU3) AS DuplicateCount FROM dosPART4) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU4 IS NULL AND HAM_KODU3 IS NOT NULL
END; 

IF(EXISTS(SELECT 1 FROM dbo.dosPART5)) BEGIN
INSERT INTO dosPART5 (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2,BIRIM_MIKTAR2,HAM_KODU3,BIRIM_MIKTAR3, HAM_KODU4,BIRIM_MIKTAR4) SELECT * FROM dosPART4;
WITH CTE (HAM_KODU4,BIRIM_MIKTAR4,HAM_KODU5, DuplicateCount) AS (SELECT HAM_KODU4, BIRIM_MIKTAR4, HAM_KODU5, ROW_NUMBER() OVER (PARTITION BY HAM_KODU4 ORDER BY HAM_KODU4) AS DuplicateCount FROM dosPART5) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU5 IS NULL AND HAM_KODU4 IS NOT NULL
END;

IF(EXISTS(SELECT 1 FROM dbo.dosPART6)) BEGIN
INSERT INTO dosPART6 (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2,BIRIM_MIKTAR2,HAM_KODU3,BIRIM_MIKTAR3, HAM_KODU4,BIRIM_MIKTAR4,HAM_KODU5,BIRIM_MIKTAR5) SELECT * FROM dosPART5;
WITH CTE (HAM_KODU5,BIRIM_MIKTAR5,HAM_KODU6, DuplicateCount) AS (SELECT HAM_KODU5, BIRIM_MIKTAR5, HAM_KODU6, ROW_NUMBER() OVER (PARTITION BY HAM_KODU5 ORDER BY HAM_KODU5) AS DuplicateCount FROM dosPART6) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU6 IS NULL AND HAM_KODU5 IS NOT NULL
END;

IF(EXISTS(SELECT 1 FROM dbo.dosPART7)) BEGIN
INSERT INTO dosPART7 (HAM_KODU1,BIRIM_MIKTAR1,HAM_KODU2,BIRIM_MIKTAR2,HAM_KODU3,BIRIM_MIKTAR3, HAM_KODU4,BIRIM_MIKTAR4,HAM_KODU5,BIRIM_MIKTAR5,HAM_KODU6,BIRIM_MIKTAR6) SELECT * FROM dosPART6;
WITH CTE (HAM_KODU6,BIRIM_MIKTAR6,HAM_KODU7, DuplicateCount) AS (SELECT HAM_KODU6, BIRIM_MIKTAR6, HAM_KODU7, ROW_NUMBER() OVER (PARTITION BY HAM_KODU6 ORDER BY HAM_KODU6) AS DuplicateCount FROM dosPART7) DELETE FROM CTE WHERE DuplicateCount > 1 AND HAM_KODU7 IS NULL AND HAM_KODU6 IS NOT NULL
END;




--ÜRÜN AÐAÇLARINI OLUÞTUR
IF OBJECT_ID('dbo.AGAC1', 'U') IS NOT NULL DROP TABLE dbo.AGAC1; 
IF OBJECT_ID('dbo.AGAC2', 'U') IS NOT NULL DROP TABLE dbo.AGAC2; 
IF OBJECT_ID('dbo.AGAC3', 'U') IS NOT NULL DROP TABLE dbo.AGAC3; 
IF OBJECT_ID('dbo.AGAC4', 'U') IS NOT NULL DROP TABLE dbo.AGAC4; 
IF OBJECT_ID('dbo.AGAC5', 'U') IS NOT NULL DROP TABLE dbo.AGAC5; 
IF OBJECT_ID('dbo.AGAC6', 'U') IS NOT NULL DROP TABLE dbo.AGAC6; 
IF OBJECT_ID('dbo.AGAC7', 'U') IS NOT NULL DROP TABLE dbo.AGAC7; 
IF OBJECT_ID('dbo.AGAC8', 'U') IS NOT NULL DROP TABLE dbo.AGAC8; 
IF OBJECT_ID('dbo.siparisAgacdos', 'U') IS NOT NULL DROP TABLE dbo.siparisAgacdos;

--AGAC1
select a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, b.HAM_KODU AS HAM_KODU1, b.MIKTAR as BIRIM_MIKTAR1 INTO AGAC1 from SIPMAMULdos a left join TBLSTOKURM b ON a.MAMUL_KODU=b.MAMUL_KODU
--AGAC2
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, b.HAM_KODU AS HAM_KODU2, b.MIKTAR AS BIRIM_MIKTAR2 INTO AGAC2 from AGAC1 a left join TBLSTOKURM b ON a.HAM_KODU1=b.MAMUL_KODU 
--AGAC3
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, b.HAM_KODU AS HAM_KODU3, b.MIKTAR AS BIRIM_MIKTAR3 INTO AGAC3 from AGAC2 a left join TBLSTOKURM b ON a.HAM_KODU2=b.MAMUL_KODU 
--AGAC4
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3, b.HAM_KODU AS HAM_KODU4, b.MIKTAR AS BIRIM_MIKTAR4 INTO AGAC4 from AGAC3 a left join TBLSTOKURM b ON a.HAM_KODU3=b.MAMUL_KODU 
--AGAC5
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4, b.HAM_KODU AS HAM_KODU5, b.MIKTAR AS BIRIM_MIKTAR5 INTO AGAC5 from AGAC4 a left join TBLSTOKURM b ON a.HAM_KODU4=b.MAMUL_KODU  
--AGAC6
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5, b.HAM_KODU AS HAM_KODU6, b.MIKTAR AS BIRIM_MIKTAR6 INTO AGAC6 from AGAC5 a left join TBLSTOKURM b ON a.HAM_KODU5=b.MAMUL_KODU  
--AGAC7
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5, a.HAM_KODU6,a.BIRIM_MIKTAR6, b.HAM_KODU AS HAM_KODU7, b.MIKTAR AS BIRIM_MIKTAR7 INTO AGAC7 from AGAC6 a left join TBLSTOKURM b ON a.HAM_KODU6=b.MAMUL_KODU  
--AGAC8
SELECT a.SIRA_NO, a.PLAN_ADI, a.SIP_NO,a.SIP_SIRA, a.MAMUL_KODU,a.SIPMIKTAR, a.HAM_KODU1, a.BIRIM_MIKTAR1, a.HAM_KODU2,a.BIRIM_MIKTAR2, a.HAM_KODU3, a.BIRIM_MIKTAR3,a.HAM_KODU4,a.BIRIM_MIKTAR4,a.HAM_KODU5,a.BIRIM_MIKTAR5, a.HAM_KODU6,a.BIRIM_MIKTAR6, a.HAM_KODU7,a.BIRIM_MIKTAR7, b.HAM_KODU AS HAM_KODU8, b.MIKTAR AS BIRIM_MIKTAR8 INTO AGAC8 from AGAC7 a left join TBLSTOKURM b ON a.HAM_KODU7=b.MAMUL_KODU  

-- VAR OLAN EN UZUN ÜRÜN AÐACINI BUL DÝÐERLERÝNÝ SÝL
IF(EXISTS(SELECT HAM_KODU8 FROM dbo.AGAC8 WHERE HAM_KODU8 IS NOT NULL)) BEGIN SELECT * INTO siparisAgacdos from AGAC8 END; 
 ELSE IF (EXISTS(SELECT HAM_KODU7 FROM dbo.AGAC7 WHERE HAM_KODU7 IS NOT NULL)) begin DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC7 end;  
 ELSE IF (EXISTS(SELECT HAM_KODU6 FROM dbo.AGAC6 WHERE HAM_KODU6 IS NOT NULL)) begin DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC6 END ;
 ELSE IF (EXISTS(SELECT HAM_KODU5 FROM dbo.AGAC5 WHERE HAM_KODU5 IS NOT NULL)) begin DROP TABLE AGAC6 DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC5 END;  
 ELSE IF (EXISTS(SELECT HAM_KODU4 FROM dbo.AGAC4 WHERE HAM_KODU4 IS NOT NULL)) begin DROP TABLE AGAC5 DROP TABLE AGAC6 DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC4 END;  
 ELSE IF (EXISTS(SELECT HAM_KODU3 FROM dbo.AGAC3 WHERE HAM_KODU3 IS NOT NULL)) begin DROP TABLE AGAC4 DROP TABLE AGAC5 DROP TABLE AGAC6 DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC3 END;  
 ELSE IF (EXISTS(SELECT HAM_KODU2 FROM dbo.AGAC2 WHERE HAM_KODU2 IS NOT NULL)) begin DROP TABLE AGAC3 DROP TABLE AGAC4 DROP TABLE AGAC5 DROP TABLE AGAC6 DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC2 END;  
 ELSE IF (EXISTS(SELECT HAM_KODU1 FROM dbo.AGAC1 WHERE HAM_KODU1 IS NOT NULL)) begin DROP TABLE AGAC2 DROP TABLE AGAC3 DROP TABLE AGAC4 DROP TABLE AGAC5 DROP TABLE AGAC6 DROP TABLE AGAC7 DROP TABLE AGAC8 SELECT * INTO siparisAgacdos from AGAC1 END;  

 --PLAN DAHÝLÝNDEKÝ SÜTUNLARI OLUÞTURMAK ÝÇÝN ÜRÜN AÐACINDA VAR OLAN TÜM PLAN ÝSÝMLERÝNÝ TEKÝL OLARAK BÝR TABLOYA AT
IF OBJECT_ID('dbo.siparisSolodos', 'U') IS NOT NULL DROP TABLE siparisSolodos;
select distinct PLAN_ADI,SIRA_NO into siparisSolodos from siparisAgacdos;


---- PLAN DAHÝLÝNDEKÝ SÜTÜNLARI OLUÞTUR  --SÜTUNLARIN HESAP TABLOSUNDAKÝ SÜTUNLARLA EÞLEÞMESÝ ÝÇÝN HAM KODU KULLAN
IF OBJECT_ID('dbo.SIPCOLUMNdos', 'U') IS NOT NULL DROP TABLE SIPCOLUMNdos;
CREATE table SIPCOLUMNdos (HAM_KODU nvarchar(max));
declare @columnname nvarchar(250);
declare @limiter int;
select @limiter = count(PLAN_ADI) FROM siparisSolodos;
declare @loopcounter int;
set @loopcounter = 1;
WHILE @loopcounter<@limiter+1 
BEGIN
	WITH Az7 AS (SELECT PLAN_ADI,SIRA_NO FROM siparisSolodos)
	SELECT @columnname = CONVERT (NVARCHAR (250),PLAN_ADI) FROM Az7 WHERE @loopcounter=SIRA_NO;
		declare @sql nvarchar(150)='ALTER TABLE SIPCOLUMNdos ADD '
		declare @sqla nvarchar(150)= @columnname
		declare @sqlb nvarchar (150)= ' float null'
		declare @sqlc nvarchar (max) = @sql+@sqla+@sqlb
		exec sp_executesql @sqlc;
	SET @loopcounter=@loopcounter+1;
end;

GO
--!ÖNEMLÝ! HER HESAPLAMADA AÐAÇ NUMARASININ KONTROL EDÝLMESÝ GEREKÝYOR. GEREKÝRSE HAM_KODUX VE BIRIM_MIKTARX ADEDÝNÝ REVÝZE ET 
--PLAN DAHÝLÝNDEKÝ HAM KODLARINI BUL
IF OBJECT_ID('dbo.SIPHAMBIRIMdos', 'U') IS NOT NULL DROP TABLE SIPHAMBIRIMdos;
SELECT a.SIRA_NO,a.PLAN_ADI, COALESCE(HAM_KODU6,HAM_KODU5,HAM_KODU4,HAM_KODU3,HAM_KODU2,HAM_KODU1) AS HAM_KODU,(ISNULL(SIPMIKTAR,1)*ISNULL(BIRIM_MIKTAR1,1)*ISNULL(BIRIM_MIKTAR2,1)*ISNULL(BIRIM_MIKTAR3,1)*ISNULL(BIRIM_MIKTAR4,1)*ISNULL(BIRIM_MIKTAR5,1)*ISNULL(BIRIM_MIKTAR6,1)) AS BIRIM_MIKTAR INTO SIPHAMBIRIMdos FROM siparisAgacdos a 
DECLARE @SIRA_NO INT;
DECLARE @HAM_KODU NVARCHAR(max);
DECLARE @MIKTAR NVARCHAR(50);
DECLARE @PLAN_ADI NVARCHAR(250);
DECLARE sql_cursor CURSOR FOR select PLAN_ADI,HAM_KODU,BIRIM_MIKTAR FROM SIPHAMBIRIMdos where HAM_KODU LIKE 'HM%' OR HAM_KODU LIKE '7300808%';
OPEN sql_cursor;
FETCH NEXT FROM sql_cursor INTO @PLAN_ADI,@HAM_KODU,@MIKTAR
WHILE (@@FETCH_STATUS = 0)
BEGIN
	FETCH NEXT FROM sql_cursor INTO @PLAN_ADI,@HAM_KODU,@MIKTAR	
	DECLARE @SQL2 NVARCHAR (MAX) ='INSERT INTO SIPCOLUMNdos ('+@PLAN_ADI+',HAM_KODU) VALUES('+@MIKTAR+','''+@HAM_KODU+''')' 
	exec sp_executesql @SQL2
END;
CLOSE sql_cursor
deallocate sql_cursor;

GO

select * from SIPCOLUMNdos where ham_kodu like '%9563'

--HAMKODU BÝRÝM MÝKTARLARINI PLANLARA DAÐIT
declare @loop int = 1;
declare @collength int;
declare @column nvarchar(max);
select @collength = count(PLAN_ADI) FROM siparisSolodos;
declare @sql4 nvarchar(max);
set @sql4='';


IF OBJECT_ID('dbo.SIPARISTABLOSUdos', 'U') IS NOT NULL DROP TABLE SIPARISTABLOSUdos;	
WHILE @loop<@collength+1 
BEGIN
	SELECT @column = PLAN_ADI FROM siparisSolodos WHERE @loop=SIRA_NO ORDER BY SIRA_NO;
	declare @sql3 nvarchar(max)='select HAM_KODU, ';
	SET @sql4= @sql4+'SUM(CAST ('+@column+' AS FLOAT)) AS '+@column+',';
	declare @sql5 nvarchar(max)=' INTO SIPARISTABLOSUdos FROM SIPCOLUMNdos GROUP BY HAM_KODU';
	SET @loop=@loop+1;
end;
declare @sql6 nvarchar(max)= @sql3+substring (@sql4,1,len(@sql4)-1)+@sql5
exec sp_executesql @sql6;

GO
--!ÖNEMLÝ! HER HESAPLAMADA AÐAÇ NUMARASININ KONTROL EDÝLMESÝ GEREKÝYOR. GEREKÝRSE HAM_KODUX VE BIRIM_MIKTARX ADEDÝNÝ REVÝZE ET 
--ÝÞ EMRÝ KALAN ÝHTÝYACI HESAPLATMAK ÝÇÝN HM KODLARINI VE HM KODLARINA ÝHTÝYAÇ DUYAN STOKLARI KALANÝHTÝYAÇ TABLOSUNA AT

IF OBJECT_ID('dbo.PLANIEIHTIYACdos', 'U') IS NOT NULL DROP TABLE PLANIEIHTIYACdos;

--PLANLARDA BULUNAN HAM KODLARINDA AÝT ÝÞ EMRÝ KALAN ÝHTÝYAÇLARI BUL  
WITH HAMKODUISEMRI AS (SELECT DISTINCT PLAN_ADI, COALESCE(HAM_KODU6,HAM_KODU5,HAM_KODU4,HAM_KODU3,HAM_KODU2,HAM_KODU1) AS HAM_KODU, 
COALESCE(g.ISEMRINO,f.ISEMRINO,e.ISEMRINO,d.ISEMRINO,c.ISEMRINO,b.ISEMRINO) AS ISEMRI 
FROM siparisAgacdos a
LEFT JOIN TBLISEMRI b on a.HAM_KODU1=b.STOK_KODU AND a.SIP_NO=b.SIPARIS_NO AND a.SIP_SIRA=b.SIPKONT
LEFT JOIN TBLISEMRI c on a.HAM_KODU2=c.STOK_KODU AND b.REFISEMRINO=c.REFISEMRINO 
LEFT JOIN TBLISEMRI d on a.HAM_KODU3=d.STOK_KODU AND b.REFISEMRINO=d.REFISEMRINO 
LEFT JOIN TBLISEMRI e on a.HAM_KODU4=e.STOK_KODU AND b.REFISEMRINO=e.REFISEMRINO 
LEFT JOIN TBLISEMRI f on a.HAM_KODU5=f.STOK_KODU AND b.REFISEMRINO=f.REFISEMRINO 
LEFT JOIN TBLISEMRI g on a.HAM_KODU6=f.STOK_KODU AND b.REFISEMRINO=f.REFISEMRINO 
where COALESCE(HAM_KODU6,HAM_KODU5,HAM_KODU4,HAM_KODU3,HAM_KODU2,HAM_KODU1) LIKE 'HM%' OR COALESCE(HAM_KODU6,HAM_KODU5,HAM_KODU4,HAM_KODU3,HAM_KODU2,HAM_KODU1) LIKE '7300808%'),
URETSON AS (SELECT URETSON_SIPNO,URETSON_MAMUL,SUM(URETSON_MIKTAR) AS URETSON_MIKTAR FROM TBLSTOKURS GROUP BY URETSON_SIPNO,URETSON_MAMUL)
SELECT a.PLAN_ADI,a.HAM_KODU,SUM(isnull(cast (b.miktar*c.miktar as float),0) - isnull(cast (d.uretson_miktar*c.miktar as float),0)) as KALANIHTIYAC INTO PLANIEIHTIYACdos FROM HAMKODUISEMRI a 
LEFT JOIN TBLISEMRI b ON a.ISEMRI=b.ISEMRINO
LEFT JOIN TBLISEMRIREC c ON a.ISEMRI=c.ISEMRINO AND b.STOK_KODU=c.MAMUL_KODU and a.HAM_KODU=c.HAM_KODU
left join uretson d on a.ISEMRI=d.URETSON_SIPNO AND b.STOK_KODU=d.URETSON_MAMUL
GROUP BY a.PLAN_ADI,a.HAM_KODU 
GO


DECLARE @PLAN_ADI NVARCHAR(250);
DECLARE @HAM_KODU NVARCHAR(50);
DECLARE @IEKALAN FLOAT;
DECLARE sql_cursor CURSOR FOR select PLAN_ADI,HAM_KODU,KALANIHTIYAC FROM PLANIEIHTIYACdos;
OPEN sql_cursor;
FETCH NEXT FROM sql_cursor INTO @PLAN_ADI,@HAM_KODU,@IEKALAN
WHILE (@@FETCH_STATUS = 0)
BEGIN
	FETCH NEXT FROM sql_cursor INTO @PLAN_ADI,@HAM_KODU,@IEKALAN	
	DECLARE @SQL12 NVARCHAR (MAX) ='UPDATE SIPARISTABLOSUdos SET '+@PLAN_ADI+'=';  
	DECLARE @SQL13 NVARCHAR (MAX) = @IEKALAN;
	DECLARE @SQL14 NVARCHAR (MAX) = ' WHERE HAM_KODU='''+@HAM_KODU +'''';
	DECLARE @SQL15 NVARCHAR (MAX)  = @SQL12+@SQL13+@SQL14
	exec sp_executesql @SQL15
END;
CLOSE sql_cursor
deallocate sql_cursor

  
