use VITA2022
go

DECLARE @STN_UZN INT;
DECLARE @STN_UZN_VARYANT INT;
DECLARE @SAY INT=1;			
DECLARE @SAY_VARYANT INT=1;		
DECLARE @SABLON_KOD NVARCHAR(11);
DECLARE @VARYANT_KOD NVARCHAR(60);
DECLARE @EN float;
DECLARE @EN_VARYANT float;
DECLARE @BOY float;
DECLARE @BOY_VARYANT float;
DECLARE @GENISLIK float;
DECLARE @GENISLIK_VARYANT float; 
DECLARE @BIRIM_AGIRLIK FLOAT;
DECLARE @BIRIM_AGIRLIK_VARYANT FLOAT;
DECLARE @KULL1N FLOAT; 
DECLARE @SQL NVARCHAR(MAX);
DECLARE @SQL2 NVARCHAR(MAX);
DECLARE @SQL3 NVARCHAR(MAX);
DECLARE @SQL4 NVARCHAR(MAX);
 
 
WITH TABLO_UZUNLUGU AS (select DISTINCT URETICI_KODU from TBLSTSABIT where URETICI_KODU IS NOT NULL and URETICI_KODU NOT LIKE 'Y%' and URETICI_KODU NOT LIKE '' and STOK_KODU NOT LIKE 'H%' AND URETICI_KODU NOT LIKE 'M%')	
SELECT @STN_UZN = count(URETICI_KODU) FROM TABLO_UZUNLUGU;

WHILE @SAY<@STN_UZN+1
BEGIN 
	WITH SABLONGETIR AS (select DISTINCT URETICI_KODU from TBLSTSABIT where URETICI_KODU IS NOT NULL and URETICI_KODU NOT LIKE 'Y%' and URETICI_KODU NOT LIKE '' and STOK_KODU NOT LIKE 'H%' AND URETICI_KODU NOT LIKE 'M%'),
	SIRANOBUL AS (SELECT URETICI_KODU, ROW_NUMBER() over ( ORDER BY URETICI_KODU) AS SIRANO FROM SABLONGETIR)
	SELECT @SABLON_KOD = URETICI_KODU FROM SIRANOBUL WHERE @SAY=SIRANO; 

	SELECT @EN = CAST(EN AS float) FROM TBLSTSABIT WHERE STOK_KODU=@SABLON_KOD; 
	
	SELECT @BOY = CAST(BOY AS float) FROM TBLSTSABIT WHERE STOK_KODU=@SABLON_KOD;
	
	SELECT @GENISLIK = CAST(GENISLIK AS float) FROM TBLSTSABIT WHERE STOK_KODU=@SABLON_KOD; 
	
	SELECT @BIRIM_AGIRLIK = CAST(BIRIM_AGIRLIK AS float) FROM TBLSTSABIT WHERE STOK_KODU=@SABLON_KOD; 

	SET @KULL1N=(@EN/1000)*(@BOY/1000)*(@GENISLIK/1000);
	SET @SQL='UPDATE TBLSTSABITEK SET KULL1N='+convert(varchar(50), @KULL1N)+' WHERE STOK_KODU='''+@SABLON_KOD+''''
	exec sp_executesql @SQL
	
			SET @SAY_VARYANT=1;
			SELECT @STN_UZN_VARYANT = CASE WHEN COUNT(STOK_KODU)=0 THEN 0 ELSE COUNT(STOK_KODU) END FROM TBLSTSABIT WHERE URETICI_KODU=@SABLON_KOD
			WHILE @SAY_VARYANT<@STN_UZN_VARYANT+1
			BEGIN

				WITH PARAMETRE_AL_VARYANT AS (SELECT STOK_KODU, ROW_NUMBER() over (ORDER BY STOK_KODU) AS SIRANO from TBLSTSABIT WHERE URETICI_KODU=@SABLON_KOD)  
				SELECT @VARYANT_KOD = STOK_KODU FROM PARAMETRE_AL_VARYANT WHERE @SAY_VARYANT=SIRANO 
				SET @SQL2='UPDATE TBLSTSABITEK SET KULL1N='+convert(varchar(50), @KULL1N)+' WHERE STOK_KODU='''+@VARYANT_KOD+''''
				SET @SQL3='UPDATE TBLSTSABIT SET EN='+convert(varchar(50), @EN)+', BOY='+convert(varchar(50), @BOY)+', GENISLIK='+convert(varchar(50), @GENISLIK)+', BIRIM_AGIRLIK='+convert(varchar(50), @BIRIM_AGIRLIK)+' WHERE STOK_KODU='''+@VARYANT_KOD+''''
				SET @SQL4=@SQL2+@SQL3
				exec sp_executesql @SQL4
				SET @SAY_VARYANT=@SAY_VARYANT+1;

			END;
	SET @SAY=@SAY+1;
END;

